
server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: configServer
          uri: https://github.com/Kalek5412/microservice-feign
          search-paths: config-sata
  application:
    name: config-server

